name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # 3. Permisos para gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Compilar proyecto (sin necesidad de DB)
      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon


