name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Dar permisos al gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Compilar con gradlew desde la raíz del repo
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./rdg7/rdg7
